spring:
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:20000

dubbo:
  application:
    name: service-abis-server
    # qos-port: 33333
  scan:
    # 包扫描
    base-packages: com.example.serviceabisserver.service
  protocol:
    name: dubbo # 指定通信协议
    id: dubbo
    # port: 20882 # 通信端口  这里指的是与消费者间的通信协议与端口
  registry.address: nacos://localhost:8848
  cloud:
    # 订阅的提供者名称
    subscribed-services: service-pri-server
  consumer:
    loadbalance: roundrobin
    check: false
  config-center:
    address: nacos://localhost:8848
