server.port: 20010

logging:
  level.com.example.cloudzuul: info
  file.name: ${spring.application.name}.log

spring:
  application.name: cloud-zuul
  zipkin:
    enabled: true
    base-url: http://localhost:9411/
    locator.discovery.enabled: true
    service.name: cloud-zuul
    sender.type: web # kafka/rabbit/web
  sleuth:
    web.client.enabled: true
    # 100%的概率将链路的数据上传给Zipkin Server，在默认的情况下，该值为0.1
    sampler.probability: 1.0
  redis:
    host: host-application
    port: 6379
#是否开启重试功能
zuul.retryable: true

management:
  # 暴露xxx端点，如需暴露多个，用,分隔；如需暴露所有端点，用'*'
  endpoints.web.exposure.include: '*'
  endpoint:
    health.show-details: always
    shutdown.enabled: true

