server.port: 20040
spring:
  application.name: admin-server
  # profiles.active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#暴露所有监控端点
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS #总是展示详情信息
